# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/Ace-Radom"
    weight     = 10

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/Hisaki03492862"
    weight     = 10

    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "photography"
    name       = "Photography"
    url        = "https://ace-radom.github.io/photography/"
    weight     = 999

    [social.params]
        icon = "camera-share"
