import json
import os
import re
import requests
import sys

from pathlib import Path

SUPPORTED_LOCALES = [
    "ar", "be", "bg", "bp",
    "cs", "de", "en", "es",
    "fa", "fi", "fr", "it",
    "ja", "ko", "mk", "pl",
    "ro", "ru", "th", "tr",
    "ua", "vi", "zh-tw",
    "zh"
]

def main() -> None:
    target_locale = sys.argv[1]
    if target_locale not in SUPPORTED_LOCALES:
        print(f"locale `{target_locale}` not supported.")
        exit(1)

    remark42_dir = Path(__file__).resolve().parent.parent / "remark42"
    locales_dir = remark42_dir / "locales"
    target_locale_json_path = locales_dir / f"{target_locale}.json"
    if not Path.exists(target_locale_json_path) or not Path.is_file(target_locale_json_path):
        print(f"locale json `{target_locale_json_path}` not exist or is not a file.")
        exit(1)
    # check locale json exist
        
    with open(target_locale_json_path, 'r', encoding='utf-8') as rf:
        target_locale_data = json.load(rf)
        target_locale_str = json.dumps(target_locale_data, separators = (',', ':'), ensure_ascii = False).replace("\\", "\\\\").replace("'", "\\'")
    # read locale json & write to str

    target_mjs_url = f"https://remark42.ace-radom.io/web/{target_locale}.mjs"
    headers = {
        "X-Request-From-Generator": "1"
    }
    with requests.get(target_mjs_url, headers = headers) as response:
        response.raise_for_status()
        mjs_src = response.text
    # get original mjs from server

    chunk_match = re.search(r"\.push\(\[\[(\d+)\]", mjs_src)
    if not chunk_match:
        print("chunk id not found from mjs.")
        exit(1)
    chunk_id = chunk_match.group(1)
    # get chunk id

    module_match = re.search(r"\{(\d+)\(e\)\{", mjs_src)
    if not module_match:
        print("module id not found from mjs.")
        exit(1)
    module_id = module_match.group(1)
    # get module id

    target_locale_mjs_str = (
        f"/**\n"
        f" * Generated by `~/tools/compile_remark42_locale.py`\n"
        f" * DO NOT EDIT!!!\n"
        f" * This file has replaced the original `{target_locale}.mjs` file\n"
        f" */\n\n"
        f"\"use strict\";"
        f"(self.webpackChunk_remark42_app="
        f"self.webpackChunk_remark42_app||[])"
        f".push([[{chunk_id}],"
        f"{{{module_id}(e){{"
        f"e.exports=JSON.parse('{target_locale_str}')"
        f"}}"
        f"}}]);"
    )
    scripts_dir = remark42_dir / "scripts"
    target_locale_mjs_path = scripts_dir / f"{target_locale}.mjs"
    with open(target_locale_mjs_path, 'w', encoding='utf-8') as wf:
        wf.write(target_locale_mjs_str)

if __name__ == "__main__":
    main()
